#!/usr/bin/env python3
"""Generate the bank-scale nightbank estate (estate/bank/) from the same
topology as the hand-written small profile: 3 regions x asset classes x
valuation shards. Deterministic -- no timestamps, sleeps derived from job
names -- so regeneration is byte-stable and the checked-in output diffs
cleanly.

    uv run python generate.py [--asset-classes 8] [--shards 8]

Defaults produce ~520 jobs. The launcher runs it with the same properties
file as the small estate (`nightbank up --estate bank`).
"""

from __future__ import annotations

import zlib
from pathlib import Path

import typer

BASE = Path(__file__).resolve().parent
OUT = BASE / "estate" / "bank"
REGIONS = {  # region -> (timezone, price/custody file prefix)
    "APAC": "Asia/Tokyo",
    "EMEA": "Europe/Zurich",
    "AMER": "America/New_York",
}
DEFAULT_ACS = ["EQ", "GOV", "CRP", "MMK", "FXO", "CMD", "IRD", "CNV"]


def nap(name: str) -> int:
    """Deterministic 6..18s fake-work duration per job name."""
    return 6 + zlib.crc32(name.encode()) % 13


class Jil:
    def __init__(self, header: str) -> None:
        self.parts = [
            f"/* {header}\n   GENERATED by generate.py -- edit the generator, not this file. */\n"
        ]

    def job(
        self,
        name: str,
        job_type: str,
        *,
        box: str | None = None,
        command: str | None = None,
        machine: str | None = None,
        condition: str | None = None,
        extra: list[str] = [],
    ) -> None:
        lines = [f"insert_job: {name}", f"job_type: {job_type}"]
        if box:
            lines.append(f"box_name: {box}")
        if condition:
            lines.append(f"condition: {condition}")
        if command:
            lines.append(f"command: {command}")
        if machine:
            lines.append(f"machine: {machine}")
        lines.append("owner: ~{$OWNER}~")
        if job_type == "c":
            lines.append("profile: ~{$NB_PROFILE}~")
        lines.append(f"std_out_file: ~{{$NB_LOGS}}~/{name}.out")
        lines.append(f"std_err_file: ~{{$NB_LOGS}}~/{name}.err")
        lines.extend(extra)
        self.parts.append("\n".join(lines) + "\n")

    def raw(self, text: str) -> None:
        self.parts.append(text.rstrip() + "\n")

    def write(self, path: Path) -> None:
        path.write_text("\n".join(self.parts))


def work(name: str, consume: list[str] = [], produce: list[str] = [], flags: str = "") -> str:
    cmd = f"fakework {name} --sleep {nap(name)}"
    for rel in consume:
        cmd += f" --consume {rel}"
    for rel in produce:
        cmd += f" --produce {rel}"
    return cmd + (f" {flags}" if flags else "")


def gen_region(region: str, tz: str, acs: list[str], shards: int) -> Jil:
    r = region.lower()
    jil = Jil(
        f"{region} -- bank-scale region: {len(acs)} asset classes x {shards} valuation shards."
    )
    jil.job(
        f"{region}_EOD_B",
        "b",
        extra=[
            "date_conditions: 1",
            "days_of_week: all",
            "exclude_calendar: HOL_GLOBAL",
            f'start_times: "~{{$EOD_{region}}}~"',
            f"timezone: {tz}",
            'must_complete_times: "+30"',
        ],
    )

    eod = f"{region}_EOD_B"
    jil.job(f"{region}_EXE_B", "b", box=eod)
    freeze = f"{region}_EXE_ORDER_FREEZE_C"
    jil.job(
        freeze,
        "c",
        box=f"{region}_EXE_B",
        machine="exe_gw",
        command=work(freeze, produce=[f"exe/{r}/orders_frozen.flag"]),
    )
    for ac in acs:
        name = f"{region}_EXE_{ac}_TRADES_C"
        jil.job(
            name,
            "c",
            box=f"{region}_EXE_B",
            machine="exe_gw",
            condition=f"s({freeze})",
            command=work(
                name,
                consume=[f"exe/{r}/orders_frozen.flag"],
                produce=[f"exe/{r}/{ac.lower()}_trades.csv"],
            ),
        )
    oo = f"{region}_EXE_OPEN_ORDERS_C"
    jil.job(
        oo,
        "c",
        box=f"{region}_EXE_B",
        machine="exe_gw",
        condition=f"s({freeze})",
        command=work(
            oo, consume=[f"exe/{r}/orders_frozen.flag"], produce=[f"exe/{r}/open_orders.csv"]
        ),
    )

    jil.job(f"{region}_ACC_B", "b", box=eod)
    close = f"{region}_ACC_GL_CLOSE_C"
    jil.job(
        close,
        "c",
        box=f"{region}_ACC_B",
        machine="bank_core",
        command=work(close, produce=[f"acc/{r}/gl_closed.flag"]),
        extra=["resources: (GL_DB, QUANTITY=1)"],
    )
    for ac in acs:
        name = f"{region}_ACC_{ac}_POSITIONS_C"
        jil.job(
            name,
            "c",
            box=f"{region}_ACC_B",
            machine="bank_core",
            condition=f"s({close})",
            command=work(
                name,
                consume=[f"acc/{r}/gl_closed.flag"],
                produce=[f"acc/{r}/{ac.lower()}_positions.csv"],
            ),
        )
    cash = f"{region}_ACC_CASH_C"
    jil.job(
        cash,
        "c",
        box=f"{region}_ACC_B",
        machine="bank_core",
        condition=f"s({close})",
        command=work(cash, consume=[f"acc/{r}/gl_closed.flag"], produce=[f"acc/{r}/cash.csv"]),
    )

    macros = f"{region}_INV_MACROS_C"
    jil.job(
        macros,
        "c",
        box=eod,
        machine="bank_core",
        command=work(macros, produce=[f"inv/{r}/macros.csv"]),
    )

    for ac in acs:
        name = f"{region}_UNIV_{ac}_DEMAND_C"
        jil.job(
            name,
            "c",
            box=eod,
            machine="bank_core",
            condition=f"s({region}_ACC_{ac}_POSITIONS_C) & s({macros}) & s({oo})",
            command=work(
                name,
                consume=[
                    f"acc/{r}/{ac.lower()}_positions.csv",
                    f"inv/{r}/macros.csv",
                    f"exe/{r}/open_orders.csv",
                ],
                produce=[f"univ/{r}/{ac.lower()}.csv"],
            ),
        )

    # FX rates: one region-level chain, no universe dependency.
    fx_sim = f"{region}_MKT_FX_SFTP_SIM_C"
    jil.job(
        fx_sim,
        "c",
        box=eod,
        machine="mkt_feed",
        command=work(fx_sim, produce=[f"incoming/{r}_fx.csv"]),
    )
    jil.job(
        f"{region}_MKT_FX_F",
        "f",
        box=eod,
        machine="mkt_feed",
        extra=[f"watch_file: ~{{$NB_DATA}}~/incoming/{r}_fx.csv", "watch_interval: 5"],
    )
    fx = f"{region}_MKT_FX_C"
    jil.job(
        fx,
        "c",
        box=eod,
        machine="mkt_feed",
        condition=f"s({region}_MKT_FX_F)",
        command=work(fx, consume=[f"incoming/{r}_fx.csv"], produce=[f"mkt/{r}/fx.csv"]),
    )

    for ac in acs:
        mkt_box = f"{region}_MKT_{ac}_B"
        jil.job(mkt_box, "b", box=eod, condition=f"s({region}_UNIV_{ac}_DEMAND_C)")
        sim = f"{region}_MKT_{ac}_SFTP_SIM_C"
        jil.job(
            sim,
            "c",
            box=mkt_box,
            machine="mkt_feed",
            command=work(sim, produce=[f"incoming/{r}_{ac.lower()}_prices.csv"]),
        )
        fw = f"{region}_MKT_{ac}_PX_F"
        jil.job(
            fw,
            "f",
            box=mkt_box,
            machine="mkt_feed",
            extra=[
                f"watch_file: ~{{$NB_DATA}}~/incoming/{r}_{ac.lower()}_prices.csv",
                "watch_interval: 5",
            ],
        )
        instr = f"{region}_REF_{ac}_INSTR_C"
        jil.job(
            instr,
            "c",
            box=mkt_box,
            machine="mkt_feed",
            condition=f"s({fw})",
            command=work(
                instr,
                consume=[f"univ/{r}/{ac.lower()}.csv", f"incoming/{r}_{ac.lower()}_prices.csv"],
                produce=[f"ref/{r}/{ac.lower()}_instruments.csv"],
            ),
        )
        marks = f"{region}_MKT_{ac}_MARKS_C"
        jil.job(
            marks,
            "c",
            box=mkt_box,
            machine="mkt_feed",
            condition=f"s({instr})",
            command=work(
                marks,
                consume=[f"ref/{r}/{ac.lower()}_instruments.csv"],
                produce=[f"mkt/{r}/{ac.lower()}_marks.csv"],
            ),
            extra=["term_run_time: 5"],
        )

    for ac in acs:
        ca = f"{region}_CA_{ac}_APPLY_C"
        jil.job(
            ca,
            "c",
            box=eod,
            machine="bank_core",
            condition=f"s({region}_ACC_{ac}_POSITIONS_C) & s({region}_REF_{ac}_INSTR_C)",
            command=work(
                ca,
                consume=[
                    f"acc/{r}/{ac.lower()}_positions.csv",
                    f"ref/{r}/{ac.lower()}_instruments.csv",
                ],
                produce=[f"ca/{r}/{ac.lower()}_adj.csv"],
            ),
        )

    for ac in acs:
        val_box = f"{region}_VAL_{ac}_B"
        jil.job(
            val_box,
            "b",
            box=eod,
            condition=f"s({region}_MKT_{ac}_B) & s({region}_CA_{ac}_APPLY_C) & s({fx})",
        )
        for i in range(1, shards + 1):
            shard = f"{region}_VAL_{ac}_SHARD{i}_C"
            jil.job(
                shard,
                "c",
                box=val_box,
                machine=f"val_grid_{r}",
                command=work(
                    shard,
                    consume=[
                        f"mkt/{r}/{ac.lower()}_marks.csv",
                        f"mkt/{r}/fx.csv",
                        f"ca/{r}/{ac.lower()}_adj.csv",
                    ],
                    produce=[f"val/{r}/{ac.lower()}_shard{i}.csv"],
                ),
                extra=["job_load: 40", f"priority: {10 if i == shards else 20}"],
            )

    rec_box = f"{region}_REC_B"
    jil.job(rec_box, "b", box=eod, condition=f"s({region}_EXE_B) & s({region}_ACC_B)")
    cust_sim = f"{region}_REC_CUST_SFTP_SIM_C"
    jil.job(
        cust_sim,
        "c",
        box=rec_box,
        machine="mkt_feed",
        command=work(cust_sim, produce=[f"incoming/{r}_custody.csv"]),
    )
    cust_fw = f"{region}_REC_CUST_F"
    jil.job(
        cust_fw,
        "f",
        box=rec_box,
        machine="mkt_feed",
        extra=[f"watch_file: ~{{$NB_DATA}}~/incoming/{r}_custody.csv", "watch_interval: 5"],
    )
    recs = []
    for ac in acs:
        rec = f"{region}_REC_{ac}_TRADES_C"
        recs.append(rec)
        jil.job(
            rec,
            "c",
            box=rec_box,
            machine="bank_core",
            condition=f"s({cust_fw}) & s({region}_EXE_{ac}_TRADES_C)",
            command=work(
                rec, consume=[f"incoming/{r}_custody.csv", f"exe/{r}/{ac.lower()}_trades.csv"]
            ),
            extra=["max_exit_success: 1"],
        )
    posn = f"{region}_REC_POSN_C"
    jil.job(
        posn,
        "c",
        box=rec_box,
        machine="bank_core",
        condition=f"s({cust_fw})",
        command=work(posn, consume=[f"incoming/{r}_custody.csv"]),
        extra=["resources: (GL_DB, QUANTITY=1)"],
    )
    gate = f"{region}_REC_GATE_C"
    jil.job(
        gate,
        "c",
        box=rec_box,
        machine="bank_core",
        condition=" & ".join(f"s({x})" for x in [*recs, posn]),
        command=f'dsl41 sendevent SET_GLOBAL --socket "$NIGHTBANK_SOCKET" --global RECON_{region}=CLEAN',
    )
    return jil


def gen_infra(shards: int) -> Jil:
    jil = Jil("Bank-scale infrastructure: per-region valuation grids.")
    for m in ("bank_core", "exe_gw", "mkt_feed", "ops_util"):
        jil.raw(f"insert_machine: {m}\ntype: a\nnode_name: localhost")
    grid_load = shards * 40  # one AC's shards fully concurrent per region
    for r in REGIONS:
        jil.raw(
            f"insert_machine: val_grid_{r.lower()}\ntype: a\nnode_name: localhost\n"
            f"max_load: {grid_load}"
        )
    jil.raw("insert_resource: GL_DB\nres_type: R\namount: 1")
    jil.raw("insert_resource: TAPE_DRIVE\nres_type: R\namount: 1")
    for r in REGIONS:
        jil.raw(f"insert_global: RECON_{r}\nvalue: PENDING")
    jil.raw("insert_global: SOD_DATE\nvalue: NONE")
    jil.raw("insert_xinst: PRD\nxtype: a")
    return jil


def gen_global(acs: list[str]) -> Jil:
    jil = Jil("Bank-scale global tail: risk consolidation, SOD flip, ops.")
    jil.job("GLOBAL_RISK_B", "b", condition="s(APAC_EOD_B) & s(EMEA_EOD_B) & s(AMER_EOD_B)")
    expo = "GLOBAL_RISK_EXPO_C"
    jil.job(
        expo,
        "c",
        box="GLOBAL_RISK_B",
        machine="bank_core",
        command=work(
            expo,
            consume=[f"val/{r.lower()}/{acs[0].lower()}_shard1.csv" for r in REGIONS],
            produce=["risk/exposures.csv"],
        ),
    )
    jil.job(
        "GLOBAL_RISK_VAR_C",
        "c",
        box="GLOBAL_RISK_B",
        machine="bank_core",
        condition=f"s({expo}) & s(EMEA_MKT_FX_C, 04.00)",
        command=work("GLOBAL_RISK_VAR_C", consume=["risk/exposures.csv"], produce=["risk/var.csv"]),
    )

    jil.job(
        "SOD_B",
        "b",
        condition="v(RECON_APAC) = CLEAN & v(RECON_EMEA) = CLEAN"
        " & v(RECON_AMER) = CLEAN & s(GLOBAL_RISK_B)",
    )
    jil.job(
        "SOD_PREFLIGHT_C",
        "c",
        box="SOD_B",
        machine="bank_core",
        command=work(
            "SOD_PREFLIGHT_C",
            consume=["risk/exposures.csv", "risk/var.csv"],
            produce=["pending/sod_ready.flag"],
        ),
    )
    jil.job(
        "SOD_APPROVE_C",
        "c",
        box="SOD_B",
        machine="bank_core",
        condition="s(SOD_PREFLIGHT_C)",
        command=work("SOD_APPROVE_C"),
        extra=["auto_hold: 1"],
    )
    jil.job(
        "SOD_FLIP_C",
        "c",
        box="SOD_B",
        machine="bank_core",
        condition="s(SOD_APPROVE_C)",
        command="fakework SOD_FLIP_C --sleep 3 --flip && dsl41 sendevent SET_GLOBAL"
        ' --socket "$NIGHTBANK_SOCKET" --global SOD_DATE=$(date +%F)',
    )
    jil.job(
        "SOD_WARMUP_C",
        "c",
        box="SOD_B",
        machine="bank_core",
        condition="s(SOD_FLIP_C)",
        command=work("SOD_WARMUP_C", consume=["current/sod_ready.flag"]),
    )

    jil.job("OPS_B", "b", condition="s(GLOBAL_RISK_B)")
    jil.job(
        "OPS_HOUSEKEEP_C",
        "c",
        box="OPS_B",
        machine="ops_util",
        command=work("OPS_HOUSEKEEP_C"),
        extra=["resources: (TAPE_DRIVE, QUANTITY=1)", "box_terminator: 1"],
    )
    jil.job(
        "OPS_ARCHIVE_C",
        "c",
        box="OPS_B",
        machine="ops_util",
        command=work("OPS_ARCHIVE_C"),
        extra=["resources: (TAPE_DRIVE, QUANTITY=1)"],
    )
    jil.job(
        "OPS_SPOOL_C",
        "c",
        box="OPS_B",
        machine="ops_util",
        command="fakework OPS_SPOOL_C --sleep 240",
        extra=["job_terminator: 1"],
    )
    jil.job(
        "OPS_HEARTBEAT_C",
        "c",
        machine="ops_util",
        command="fakework OPS_HEARTBEAT_C --sleep 3",
        extra=[
            "date_conditions: 1",
            "days_of_week: all",
            "start_mins: 0, 15, 30, 45",
            'run_window: "~{$HB_WINDOW}~"',
            "timezone: UTC",
        ],
    )
    jil.job(
        "OPS_LEGACY_REPORT_C",
        "c",
        machine="ops_util",
        condition="s(GLOBAL_RISK_B)",
        command=work("OPS_LEGACY_REPORT_C"),
        extra=["status: ON_ICE"],
    )
    jil.job(
        "OPS_XINST_DEMO_C",
        "c",
        machine="ops_util",
        condition="s(GROUP_TREASURY_EOD^PRD, 9999)",
        command=work("OPS_XINST_DEMO_C"),
    )
    return jil


def gen_incidents(acs: list[str]) -> str:
    """The bank estate's scripted incidents: same behaviors as the small
    profile, but the marks/trades targets are per-asset-class here -- the
    names must exist in THIS estate (the runbook's bank section maps them)."""
    ac = acs[0].upper()
    return (
        "# nightbank bank estate -- scripted incidents (JOB BEHAVIOR [ARG]).\n"
        "# GENERATED by generate.py alongside the estate: every target below\n"
        "# exists in estate/bank/. The small estate has its own file.\n"
        "\n"
        "EMEA_REC_CUST_SFTP_SIM_C    no_show\n"
        "AMER_MKT_FX_C               fail_once   5\n"
        f"EMEA_MKT_{ac}_MARKS_C          hang_once\n"
        f"APAC_REC_{ac}_TRADES_C         breaks      7\n"
    )


def main(
    asset_classes: int = typer.Option(8, "--asset-classes", min=1, max=8),
    shards: int = typer.Option(8, "--shards"),
    out: Path = typer.Option(OUT, "--out", help="Output directory."),
) -> None:
    acs = DEFAULT_ACS[:asset_classes]

    out.mkdir(parents=True, exist_ok=True)
    gen_infra(shards).write(out / "infra.jil")
    # Calendars are identical to the small estate's -- single source.
    (out / "calendars.jil").write_text((BASE / "estate" / "small" / "calendars.jil").read_text())
    for region, tz in REGIONS.items():
        gen_region(region, tz, acs, shards).write(out / f"{region.lower()}.jil")
    gen_global(acs).write(out / "global.jil")
    (out / "incidents.conf").write_text(gen_incidents(acs))
    total = sum(
        (out / f).read_text().count("insert_job:")
        for f in ("apac.jil", "emea.jil", "amer.jil", "global.jil")
    )
    typer.echo(f"estate/bank: {total} jobs ({asset_classes} asset classes x {shards} shards)")


if __name__ == "__main__":
    typer.run(main)
