# Committed-credentials scan: gitleaks over the FULL git history (fetch-depth
# 0), not just the tip -- a secret is leaked the moment it is ever committed,
# even if a later commit removes it. Free for personal-account repos (the
# GITLEAKS_LICENSE requirement applies to GitHub Organizations only).
# README's "secrets" brick badges this workflow.

name: secrets

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e # v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
